server:
  port: 8001

#myvm:
#  host: 192.168.199.215
myvm:
  host: 172.20.10.11

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率：介于0到1之间，1表示全部采集（一般设为0.5）
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://${myvm.host}:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: user
    password: passwd

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.fleexy.springcloud.entities
  configuration:
    use-actual-param-name: true

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka, http://eureka7003.com:7003/eureka
  instance:
    instance-id: paymant8001
    prefer-ip-address: true #访问路径可以显示主机ip地址

logging:
  file:
    path: E:/applogs/cloud2020/cloud-payment-service/8001/
  level:
    com.fleexy.springcloud.dao: debug
