server:
  port: 8002

#myvm:
#  host: 192.168.199.215
myvm:
  host: 172.20.10.11

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://${myvm.host}:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: user
    password: passwd

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.fleexy.springcloud.entities
  configuration:
    use-actual-param-name: true

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #集群版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka, http://eureka7003.com:7003/eureka
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: paymant8002
    prefer-ip-address: true #访问路径可以显示主机ip地址
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
#    lease-renewal-interval-in-seconds: 1
#    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认90秒），超时将剔除服务
#    lease-expiration-duration-in-seconds: 2


#logging:
#  file:
#    path: E:/applogs/cloud2020/cloud-payment-service/8002/
#  level:
#    com.fleexy.springcloud.dao: debug
