server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
#          filters:
#            - AddRequestParameter=X-Request-Id, 1024 #过滤器工厂会在匹配的请求头加上- -对请求头，名称为X- Request- Id值为1024
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
#            - After=2020-12-12T16:50:58.538+08:00[Asia/Shanghai]
#            - Cookie=username,BigT #并且Cookie是username=BigT才能访问
#            - Header=X-Request-Id, \d+ #请求头中要有X-Request-Id属性并且值为正整数的正则表达式
#            - Host=eureka7001.com:9527 #请求host必须为eureka7001.com:9527
#            - Method=GET #指定请求方式
#            - Query=username, \d+ #要有参数名称并且是正整数才能路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka